name: ğŸš€ AKS Deploy Pipeline (OIDC)

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-aks:
    runs-on: ubuntu-latest

    environment:
      name: aks-prod

    env:
      TF_ROOT_DIR: project4-enterprise-aks-devops-platform/infrastructure/aks

      TF_VAR_environment: dev
      TF_VAR_prefix: entdevops
      TF_VAR_aks_cluster_name: devops-aks
      TF_VAR_aks_resource_group: rg-devsecops-dev
      TF_VAR_rg_name: rg-devsecops-dev

      ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}

    steps:
      - name: ğŸ“¦ Checkout
        uses: actions/checkout@v4

      - name: ğŸ” Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: ğŸ” Verify Azure Login
        run: az account show --output table

      - name: âš™ï¸ Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3

      - name: ğŸ§© Terraform Init
        run: |
          cd $TF_ROOT_DIR
          terraform init -upgrade

      - name: ğŸ§® Terraform Plan
        run: |
          cd $TF_ROOT_DIR
          terraform plan -out=tfplan -input=false

      - name: ğŸš€ Terraform Apply
        run: |
          cd $TF_ROOT_DIR
          terraform apply -auto-approve tfplan
