name: ğŸš€ AKS Deploy Pipeline (OIDC)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment to deploy (dev/preprod/prod)"
        required: true
        default: "dev"

permissions:
  id-token: write       # ğŸ”¥ REQUIRED for OIDC
  contents: read

jobs:
  deploy-aks:
    runs-on: ubuntu-latest

    env:
      TF_ROOT_DIR: project4-enterprise-aks-devops-platform/infrastructure/aks
      TF_VAR_environment: dev
      TF_VAR_prefix: entdevops
      TF_VAR_acr_name: devopsacr001
      TF_VAR_image_name: sampleapp
      TF_VAR_aks_cluster_name: devops-aks
      TF_VAR_aks_resource_group: rg-devsecops-dev
      TF_VAR_rg_name: rg-devsecops-dev

      # OIDC â€” no client_secret needed
      ARM_CLIENT_ID: "8ff5b619-e748-4ffc-9cf5-b3b5a92300d6"
      ARM_TENANT_ID: "ea391d70-8ca3-4e86-beef-3feee4811c01"
      ARM_SUBSCRIPTION_ID: "98046183-6757-4572-8532-91d5dad505e2"

      TF_VAR_subscription_id: "98046183-6757-4572-8532-91d5dad505e2"
      TF_VAR_client_id: "8ff5b619-e748-4ffc-9cf5-b3b5a92300d6"
      TF_VAR_tenant_id: "ea391d70-8ca3-4e86-beef-3feee4811c01"

    steps:
      - name: ğŸ“¦ Checkout Repository
        uses: actions/checkout@v4

      - name: ğŸ” Azure Login via OIDC (NO secret)
        uses: azure/login@v2
        with:
          client-id: "8ff5b619-e748-4ffc-9cf5-b3b5a92300d6"
          tenant-id: "ea391d70-8ca3-4e86-beef-3feee4811c01"
          subscription-id: "98046183-6757-4572-8532-91d5dad505e2"
          allow-no-subscriptions: false

      - name: ğŸ” Verify Azure Connection
        run: |
          echo "Checking Azure authentication..."
          az account show --output table
          echo "âœ… Azure authentication successful!"

      - name: âš™ï¸ Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3

      - name: ğŸ§© Terraform Init
        run: |
          cd $TF_ROOT_DIR
          terraform init -upgrade

      - name: ğŸ§® Terraform Plan
        run: |
          cd $TF_ROOT_DIR
          terraform plan -out=tfplan -input=false

      - name: â³ Manual Approval before Apply
        uses: trstringer/manual-approval@v1
        with:
          approvers: sudhir81
          minimum-approvals: 1
          timeout-minutes: 30
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸš€ Terraform Apply
        run: |
          cd $TF_ROOT_DIR
          terraform apply -auto-approve tfplan

      - name: ğŸ“¤ Upload TF State
        uses: actions/upload-artifact@v4
        with:
          name: aks-tfstate
          path: ${{ env.TF_ROOT_DIR }}/terraform.tfstate
